version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "celo-org/applications"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
