image:
  repository: us-central1-docker.pkg.dev/clabs-gnosis-safe/images/safe-client-gateway
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0352ad7094f97a1e88e2610edcf38db38a2232a5

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: client-gateway.celo-safe.io
      paths:
      - path: /

  tls:
  - secretName: client-gateway-tls
    hosts:
       - client-gateway.celo-safe.io

env:
  configServiceUri: http://safe-config-service
  webhookToken: test
  rocketSecretKey: test
  exchangeApiKey: test
  txAuthToken: test

global:
  redis:
    password: testetestes

redis:
  image:
    tag: "6.2.7"
  replica:
    replicaCount: 1
